from requests_oauthlib import OAuth1Session


class TelldusInterface:
    def __init__(self, public_key, private_key, token, token_secret, base_url='http://api.telldus.com'):
        """
        Interface between the Telldus API
        :param public_key: The public KEY generated by the Telldus API
        :param private_key: The private KEY generated by the Telldus API
        :param token: The token generated by the Telldus API
        :param token_secret: The token secret KEY generated by the Telldus API
        :param base_url: Telldus API URL
        """
        self.public_key = public_key
        self.private_key = private_key
        self.token = token
        self.token_secret = token_secret

        self.base_url = base_url

        self.oauth = self.generate_temp_session()

    def generate_temp_session(self):
        """
        Generates a temporary OAuthSession to authenticate requests
        :return: OAuthSession
        """
        return OAuth1Session(client_key=self.public_key,
                             client_secret=self.private_key,
                             resource_owner_key=self.token,
                             resource_owner_secret=self.token_secret)

    def list_devices(self):
        """
        Prints information about every device available
        :return:
        """
        response = self.oauth.get(url=f'{self.base_url}/json/devices/list')

        result = response.json()['device']
        for device in result:
            print(device)

    def load_devices(self):
        """
        Gets all information needed from device list
        :return: list - [id:str, name:str, state:str]
        """
        response = self.oauth.get(url=f'{self.base_url}/json/devices/list')

        result = response.json()['device']
        return [(device['id'], device['name'], device['state']) for device in result]

    def request_action(self, request, data):
        """
        Sends an API request to the Telldus api
        :param request: str - Request added to the base url
        :param data: str - Parameters passed to the POST request
        :return: Response from the server
        """

        response = self.oauth.post(url=f'{self.base_url}/json/{request}', data=data)
        return response.json()
